services:
  - type: web
    runtime: node
    name: restaurant-prep-system
    plan: free
    buildCommand: |
      npm install --production=false
      npm run build
    startCommand: |
      npm start
    healthCheckPath: /api/health
    autoDeploy: false
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: POSTGRES_USER
        fromDatabase:
          name: prep_system_db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: prep_system_db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: prep_system_db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: prep_system_db
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: prep_system_db
          property: database
      - key: DATABASE_URL
        fromDatabase:
          name: prep_system_db
          property: connectionString
      - key: NEXT_PUBLIC_API_URL
        value: ${RENDER_EXTERNAL_URL}/api

databases:
  - name: prep_system_db
    databaseName: prep_system
    user: prep_system_user
    plan: free
    ipAllowList: [] # Only internal connections