services:
  - type: web
    name: restaurant-prep-system
    env: node
    plan: standard
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_USER
        fromDatabase:
          name: prep_system_db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: prep_system_db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: prep_system_db
          property: host
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: prep_system_db
          property: database

databases:
  - name: prep_system_db
    databaseName: prep_system
    user: prep_system_user
    plan: free
    ipAllowList: []